resolve conflict

diff --git a/.github/workflows/clamav-ci.yml b/.github/workflows/clamav-ci.yml
--- a/.github/workflows/clamav-ci.yml
+++ b/.github/workflows/clamav-ci.yml
@@ -4,27 +4,24 @@ on:
   push:
     branches:
       - main
+    paths:
+      - '.github/workflows/clamav-ci.yml'
+      - 'virus-protection/clamav/**'
+      - 'asc606-pdf-parser-website/**'
   pull_request:
     branches:
       - main
     paths:
-      - '.github/workflows/*clamav-ci.yml'
+      - '.github/workflows/clamav-ci.yml'
       - 'virus-protection/clamav/**'
       - 'asc606-pdf-parser-website/**'
 
 jobs:
   clamav-check:
-    runs-on: ubuntu-latest
-    services:
-      clamav:
-        image: clamav/clamav:stable
-        options: >-
-          --health-cmd="clamdscan --version || exit 1"
-          --health-interval=30s
-          --health-timeout=10s
-          --health-retries=5
-        ports:
-          - 3310:3310  # Port for ClamAV daemon
+    runs-on: ubuntu-24.04
+    defaults:
+      run:
+        working-directory: ${{ github.workspace }}
 
     steps:
     - name: Checkout Repository
@@ -33,26 +30,42 @@ jobs:
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v1
 
-    - name: Download Dummy PDF
-      run: wget -q -O dummy.pdf https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf
+    - name: Download Sample PDF
+      run: |
+        wget -q -O pdf_files_to_parse/sample.pdf https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf || {
+          echo "Failed to download sample PDF";
+          exit 1;
+        }
 
     - name: Start ClamAV Container
-      run: docker compose -f ${{ github.workspace }}/virus-protection/clamav/docker-compose.clamav.yml up -d clamav
+      run: docker compose -f docker-compose.yml -f ./virus-protection/clamav/docker-compose.clamav.yml up --build clamav -d
 
     - name: Wait for ClamAV to Initialize
       run: |
         echo "Waiting for ClamAV service to be healthy..."
-        until [ "`docker inspect -f {{.State.Health.Status}} clamav`" == "healthy" ]; do
+        until [ "`docker inspect -f {{.State.Health.Status}} clamav-container`" == "healthy" ]; do
           sleep 5;
         done
       shell: bash
 
     - name: Test ClamAV Scanning on Dummy PDF
       run: |
-        clamdscan --fdpass dummy.pdf | tee scan_output.log
+        echo "Copying dummy.pdf into ClamAV container..."
+        docker cp pdf_files_to_parse/sample.pdf clamav-container:/scan/sample.pdf
+
+        echo "Running clamdscan inside the container..."
+        docker exec clamav-container clamdscan --fdpass /scan/sample.pdf | tee scan_output.log
+
         if grep -q "OK$" scan_output.log; then
           echo "ClamAV scan passed successfully!"
         else
           echo "ClamAV scan failed!" && exit 1
         fi
       shell: bash
+
+    - name: Clear Workspace
+      run: |
+        docker compose -f docker-compose.yml -f ./virus-protection/clamav/docker-compose.clamav.yml down -v
+        yes | docker system prune -a
+        
+
