harden runs-on: ubuntu-24.04

diff --git a/.github/workflows/clamav-ci.yml b/.github/workflows/clamav-ci.yml
--- a/.github/workflows/clamav-ci.yml
+++ b/.github/workflows/clamav-ci.yml
@@ -14,7 +14,10 @@ on:
 
 jobs:
   clamav-check:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-24.04
+    defaults:
+      run:
+        working-directory: ${{ github.workspace }}
     services:
       clamav:
         image: clamav/clamav:stable
@@ -33,12 +36,15 @@ jobs:
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v1
 
-    - name: Download Dummy PDF
-      run: wget -q -O dummy.pdf https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf
+    - name: Download Sample PDF
+      run: |
+        wget -q -O pdf_files_to_parse/sample.pdf https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf || {
+          echo "Failed to download sample PDF";
+          exit 1;
+        }
 
     - name: Start ClamAV Container
-      run: docker compose -f virus-protection/clamav/docker-compose.clamav.yml up -d clamav
-
+      run: docker compose -f docker-compose.yml -f ./virus-protection/clamav/docker-compose.clamav.yml up --build clamav -d
 
     - name: Wait for ClamAV to Initialize
       run: |
